### ISSUE TITLE
Test trial resumability with PBT & Hyperband

### ISSUE THREAD

**Issue by Delaunay** [Epistimio/hydra_orion_sweeper#20]

**Comment by MaximilienLC** [comment]
Hey, thanks for the great package!

I was wondering if you had any update on this issue. Is it supposedly currently possible to resume trials however this feature has not yet been properly tested?

**Comment by bouthilx** [comment]
Hi! PBT is a bit tricky to use with Hydra because it relies on checkpoints being copied from one trial to another while Hydra creates new working dir for each trial and sets them as working directories for the time of the trial execution. It should be possible to use PBT (and Hyperband with checkpointing) if you set your working dir explicitly in hydra config.

@Delaunay Is this something you tested yet?

**Comment by Delaunay** [comment]
As Bouthilx pointed out you need to control the directory so the checkpoint can be found between reruns.

Maybe something like this would work:
```
hydra:
  sweep:
    dir: multirun/
    subdir: ${hydra.sweeper.experiment.name}/${hydra.sweeper.experiment.paramhash}
```

So all the HPO run will end up in the same folder.
It will create one folder per experiment name and one folder per trial parameter config.
So it should be able to find the checkpoint of a given trial.

**Comment by Delaunay** [comment]
In the case of hydra shouldn't `trial.working_dir` be the current working directory that hydra set ?

**Comment by Delaunay** [comment]
@bouthilx 
With the latest version, I believe this should work for PBT

```
hydra:
  sweep:
    dir: multirun/${hydra.sweeper.experiment.name}
    subdir: ${hydra.sweeper.experiment.trial_working_dir}/
```

**Comment by maximilienleclei** [comment]
Hey sorry for the late reply, I tried making it work w/ this simple example:

```
defaults:
  - override hydra/sweeper: orion

hydra:
  sweep:
    dir: multirun/${hydra.sweeper.experiment.name}
    subdir: ${hydra.sweeper.experiment.trial_working_dir}
  sweeper:
    params:
      x: "uniform(-10, 10)"
      epoch: "fidelity(low=1, high=2, base=1)"
    algorithm:
      type: pbt
      config:
        seed: 0
        population_size: 5
        generations: 1
x: 0
epoch: 0
```

```
import hydra
from omegaconf import DictConfig


@hydra.main(config_path=".", config_name="config")
def main(cfg: DictConfig) -> float:
    result = (cfg.x * cfg.x) ** cfg.epoch
    with open(f"{cfg.x}+{int(cfg.epoch)}.txt", "w") as f:
        f.write(str(result))
    return result


if __name__ == "__main__":
    main()
```

However, every trial's `trial_working_dir` is different (and equal to `trial`)
Example output `hydra.yaml`

```
...
trial: 4e2287fd0fedb2f7da85735f1599eff5
paramhash: b135edc909ac21e8304df5ca1bd363c5
uuid: 88208312c86311eeb13b0242ac110002
trial_working_dir: 4e2287fd0fedb2f7da85735f1599eff5
...
```

`paramhash` looks the same for trials that do not change parameters though.
